services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"  # Vue dev server端口
    volumes:
      - ./frontend/src:/app/src  # 挂载源代码，支持热更新
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vue.config.js:/app/vue.config.js
      - ./frontend/babel.config.js:/app/babel.config.js
      - frontend-node-modules:/app/node_modules  # 独立的node_modules卷
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "9000:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - backend-m2:/root/.m2
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_blog
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql-dev-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-dev
    ports:
      - "8080:80"  # 使用不同端口避免冲突
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  frontend-node-modules:
  mysql-dev-data:
  backend-m2: