services:
  backend:
    # 使用阿里云 ACR 镜像（与前端相同的 Registry/命名空间/仓库规则）
    # 为减少频繁打标签，采用 stable tag：latest（如需回滚可推送带版本号的并临时改 compose）
    image: crpi-q0fu55ysz8p6bskr.cn-beijing.personal.cr.aliyuncs.com/zshlyyyds/summer-backend:latest
    container_name: backend
    depends_on:
      - mysql
    restart: always

  mysql:
    image: crpi-q0fu55ysz8p6bskr.cn-beijing.personal.cr.aliyuncs.com/zshlyyyds/summer-mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_blog
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    image: crpi-q0fu55ysz8p6bskr.cn-beijing.personal.cr.aliyuncs.com/zshlyyyds/summer-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql-data: